language: go

go:
  - 1.8.x

install:
  - go get github.com/kylelemons/go-gypsy/yaml
  - go get github.com/gorilla/mux
  - go get google.golang.org/grpc
  - go get git.apache.org/thrift.git/lib/go/thrift
  - go get github.com/spf13/cobra
  - go get github.com/spf13/viper
  - go get github.com/bitly/go-simplejson
  - go get github.com/stretchr/testify/assert
#  - go get golang.org/x/tools/cmd/cover
#  - go get github.com/mattn/goveralls
#script:
#  - go test -v -covermode=count -coverprofile=coverage.out
#  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken LKmWen7DjWjYrvaX8N80tX9LbnCRCww8k
