language: go
sudo: false

go:
  - tip
before_install:
  - go get github.com/mattn/goveralls

install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout e73500c735917e39a8b782e0632418ab70250341 && go install && cd -
  - glide install
#  - go get golang.org/x/tools/cmd/cover
#  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
#  - cd $GOPATH/src/github.com/vaporz/turbo
#  - $HOME/gopath/bin/goveralls -repotoken LKmWen7DjWjYrvaX8N80tX9LbnCRCww8k
